# Primeras Impresiones Nova Market Dataset

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("NovaMarket_datos_crudos.csv")
df.info()

# Variables
- Se identifican 14 variables agrupadas por nivel de medición de la siguiente manera:
    - Ordinales: nivel_satisfacción, codigo_postal
    - Nominales: id_pedido, id_cliente, categoria_producto, canal, producto, correo, ciudad
    - Intervalo: fecha_compra, fecha_actualizacion_stock, edad_cliente
    - Razón: unidades, precio
        -
- Tenemos 10 variables tipo string, 3 tipo integer y 1 tipo float

In [41]:
df.head()

,id_pedido,id_cliente,fecha_compra,canal,ciudad,codigo_postal,categoria_producto,producto,precio,unidades,edad_cliente,correo,nivel_satisfaccion,fecha_actualizacion_stock
0,P00383,C0276,2026-01-03,App,Bucaramanga,68001,Belleza,Camiseta,-1742611.0,4,-19,c0276gmail.com,alto,2026-07-01
1,P00403,C0167,6/12/2026,Web,Cali,76001,Deportes,Cafetera,1828583.0,2,23,c0167@hotmail.com,MEDIO,2026-07-01
2,P00403,C0167,6/12/2026,Web,Cali,76001,Deportes,Cafetera,1828583.0,2,23,c0167@hotmail.com,MEDIO,2026-07-01
3,P00450,C0128,07/09/2026,App,bucaramanga,68001,electronica,Set bloques,787178.0,6,69,c0128@hotmail.com,MEDIO,2026-07-15
4,P00449,C0304,2025-07-19,Tienda,Bogotá,8001,Belleza,Audífonos BT,357231.0,5,67,c0304@novamarket.co,Bajo,2026-05-20

# Datos

Observamos que los datos tienen varias problematicas como formatos de fecha distintos en la misma columna, nombres de categoria con significado similar pero escritos de diferente manera, incongruencia en datos numericos que no deberian ser negativos.

In [42]:
df.shape

(620, 14)

# Dataset

Tenemos 620 registros con 14 columnas.

In [43]:
df.describe(include='all')

,id_pedido,id_cliente,fecha_compra,canal,ciudad,codigo_postal,categoria_producto,producto,precio,unidades,edad_cliente,correo,nivel_satisfaccion,fecha_actualizacion_stock
count,620,620,620,620,589,620.000000,620,620,5.990000e+02,620.000000,620.000000,516,574,620
unique,600,311,495,3,19,NaN,17,14,NaN,NaN,NaN,429,8,8
top,P00403,C0043,15/11/2027,Tienda,bucaramanga,NaN,Belleza,Perfume,NaN,NaN,NaN,c0012@hotmail.com,Alto,2026-07-15
freq,2,6,9,224,58,NaN,66,52,NaN,NaN,NaN,4,91,152
mean,NaN,NaN,NaN,NaN,NaN,31917.129032,NaN,NaN,4.888703e+06,188.682258,48.012903,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,30339.586863,NaN,NaN,4.292512e+07,1240.652475,28.668511,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,5001.000000,NaN,NaN,-2.448455e+06,-3.000000,-20.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,8001.000000,NaN,NaN,5.914020e+05,2.000000,31.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,13001.000000,NaN,NaN,1.178666e+06,3.000000,46.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,68001.000000,NaN,NaN,1.856670e+06,5.000000,63.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,76001.000000,NaN,NaN,7.730038e+08,9999.000000,200.000000,NaN,NaN,NaN

# Descripción de datos

- Hay faltantes de datos en ciudad, precio, correo, nivel_satisfacción
- Parece ser que existen outliers en varias columnas como precio, unidades, edad_cliente